In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [10]:
df=pd.read_csv('E:\\data sets dowload\\50_Startups(1).csv')

In [20]:
df.head()
df.shape

(50, 5)

In [116]:
df

R&D Spend  Administration  Marketing Spend     Profit  Florida  New York
0   165349.20       136897.80        471784.10  192261.83        0         1
1   162597.70       151377.59        443898.53  191792.06        0         0
2   153441.51       101145.55        407934.54  191050.39        1         0
3   144372.41       118671.85        383199.62  182901.99        0         1
4   142107.34        91391.77        366168.42  166187.94        1         0
5   131876.90        99814.71        362861.36  156991.12        0         1
6   134615.46       147198.87        127716.82  156122.51        0         0
7   130298.13       145530.06        323876.68  155752.60        1         0
8   120542.52       148718.95        311613.29  152211.77        0         1
9   123334.88       108679.17        304981.62  149759.96        0         0
10  101913.08       110594.11        229160.95  146121.95        1         0
11  100671.96        91790.61        249744.55  144259.40        0         0
12   93863.75       127320.38        249839.44  141585.52        1         0
13   91992.39       135495.07        252664.93  134307.35        0         0
14  119943.24       156547.42        256512.92  132602.65        1         0
15  114523.61       122616.84        261776.23  129917.04        0         1
16   78013.11       121597.55        264346.06  126992.93        0         0
17   94657.16       145077.58        282574.31  125370.37        0         1
18   91749.16       114175.79        294919.57  124266.90        1         0
19   86419.70       153514.11             0.00  122776.86        0         1
20   76253.86       113867.30        298664.47  118474.03        0         0
21   78389.47       153773.43        299737.29  111313.02        0         1
22   73994.56       122782.75        303319.26  110352.25        1         0
23   67532.53       105751.03        304768.73  108733.99        1         0
24   77044.01        99281.34        140574.81  108552.04        0         1
25   64664.71       139553.16        137962.62  107404.34        0         0
26   75328.87       144135.98        134050.07  105733.54        1         0
27   72107.60       127864.55        353183.81  105008.31        0         1
28   66051.52       182645.56        118148.20  103282.38        1         0
29   65605.48       153032.06        107138.38  101004.64        0         1
30   61994.48       115641.28         91131.24   99937.59        1         0
31   61136.38       152701.92         88218.23   97483.56        0         1
32   63408.86       129219.61         46085.25   97427.84        0         0
33   55493.95       103057.49        214634.81   96778.92        1         0
34   46426.07       157693.92        210797.67   96712.80        0         0
35   46014.02        85047.44        205517.64   96479.51        0         1
36   28663.76       127056.21        201126.82   90708.19        1         0
37   44069.95        51283.14        197029.42   89949.14        0         0
38   20229.59        65947.93        185265.10   81229.06        0         1
39   38558.51        82982.09        174999.30   81005.76        0         0
40   28754.33       118546.05        172795.67   78239.91        0         0
41   27892.92        84710.77        164470.71   77798.83        1         0
42   23640.93        96189.63        148001.11   71498.49        0         0
43   15505.73       127382.30         35534.17   69758.98        0         1
44   22177.74       154806.14         28334.72   65200.33        0         0
45    1000.23       124153.04          1903.93   64926.08        0         1
46    1315.46       115816.21        297114.46   49490.75        1         0
47       0.00       135426.92             0.00   42559.73        0         0
48     542.05        51743.15             0.00   35673.41        0         1
49       0.00       116983.80         45173.06   14681.40        0         0

In [17]:
#finding null values
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [45]:
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [47]:
#creating dummy variables
a=pd.get_dummies(df['State'])

In [48]:
a.head()

California  Florida  New York
0           0        0         1
1           1        0         0
2           0        1         0
3           0        0         1
4           0        1         0

In [52]:
#as we required only two colums so we will drop one cloumn
a=a.drop(['California'],axis=1)

In [53]:
a.head()

Florida  New York
0        0         1
1        0         0
2        1         0
3        0         1
4        1         0

In [56]:
#now cocatenating 
df=pd.concat([df,a],axis=1)

In [57]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit  Florida  \
0  165349.20       136897.80        471784.10    New York  192261.83        0   
1  162597.70       151377.59        443898.53  California  191792.06        0   
2  153441.51       101145.55        407934.54     Florida  191050.39        1   
3  144372.41       118671.85        383199.62    New York  182901.99        0   
4  142107.34        91391.77        366168.42     Florida  166187.94        1   

   New York  
0         1  
1         0  
2         0  
3         1  
4         0

In [71]:
#as we dont want states column we are removing it
df=df.drop(['State'],axis=1)

In [72]:
df.head()

R&D Spend  Administration  Marketing Spend     Profit  Florida  New York
0  165349.20       136897.80        471784.10  192261.83        0         1
1  162597.70       151377.59        443898.53  191792.06        0         0
2  153441.51       101145.55        407934.54  191050.39        1         0
3  144372.41       118671.85        383199.62  182901.99        0         1
4  142107.34        91391.77        366168.42  166187.94        1         0

In [74]:
#assigning variables
X=df.drop(['Profit'],axis=1)

In [75]:
X.head()

R&D Spend  Administration  Marketing Spend  Florida  New York
0  165349.20       136897.80        471784.10        0         1
1  162597.70       151377.59        443898.53        0         0
2  153441.51       101145.55        407934.54        1         0
3  144372.41       118671.85        383199.62        0         1
4  142107.34        91391.77        366168.42        1         0

In [77]:
#dependent variable
Y=df['Profit']

In [78]:
Y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [79]:
len(X)
len(Y)

50

# Splitig of data

In [80]:
import sklearn

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y, test_size=0.33,random_state=33)

In [83]:
xtrain.head()

R&D Spend  Administration  Marketing Spend  Florida  New York
21   78389.47       153773.43        299737.29        0         1
30   61994.48       115641.28         91131.24        1         0
48     542.05        51743.15             0.00        0         1
23   67532.53       105751.03        304768.73        1         0
43   15505.73       127382.30         35534.17        0         1

In [94]:
len(xtrain)

33

In [84]:
ytrain.head()

21    111313.02
30     99937.59
48     35673.41
23    108733.99
43     69758.98
Name: Profit, dtype: float64

# importing model

In [85]:
from sklearn.linear_model import LinearRegression

In [86]:
reg=LinearRegression()

# Fitting data to model

In [87]:
reg.fit(xtrain,ytrain)

LinearRegression()

# checking performance with traing data

In [91]:
ytrainpredict=reg.predict(xtrain)

In [93]:
ytrainpredict

array([120014.14770477,  98378.49213456,  49705.75860414, 112251.25629172,
        58840.24199426,  59175.93266598,  75028.47344079, 155729.9811042 ,
        40859.06440842,  43839.17645295,  74521.46433168,  68889.42819912,
       156825.5471798 , 137362.54162711,  95643.19889351, 117072.98262939,
       116486.48401501, 137104.4885453 , 130493.57750947,  97204.26233818,
       127315.16102354,  98788.09714621,  93644.24963172, 150551.20547314,
       114518.29242447,  72650.20644736, 180244.26552225, 157069.93382209,
       131388.71206167, 187891.36831298, 115828.79422885, 162548.10765558,
       117489.05617978])

In [95]:
len(ytrainpredict)

33

In [98]:
dataframe=pd.DataFrame({"Ytrain":ytrain,'ypredict':ytrainpredict})

In [99]:
dataframe

Ytrain       ypredict
21  111313.02  120014.147705
30   99937.59   98378.492135
48   35673.41   49705.758604
23  108733.99  112251.256292
43   69758.98   58840.241994
44   65200.33   59175.932666
41   77798.83   75028.473441
8   152211.77  155729.981104
47   42559.73   40859.064408
49   14681.40   43839.176453
36   90708.19   74521.464332
42   71498.49   68889.428199
6   156122.51  156825.547180
10  146121.95  137362.541627
32   97427.84   95643.198894
16  126992.93  117072.982629
22  110352.25  116486.484015
11  144259.40  137104.488545
12  141585.52  130493.577509
31   97483.56   97204.262338
13  134307.35  127315.161024
33   96778.92   98788.097146
35   96479.51   93644.249632
14  132602.65  150551.205473
19  122776.86  114518.292424
38   81229.06   72650.206447
3   182901.99  180244.265522
9   149759.96  157069.933822
18  124266.90  131388.712062
2   191050.39  187891.368313
24  108552.04  115828.794229
7   155752.60  162548.107656
20  118474.03  117489.056180

In [100]:
dataframe

Ytrain       ypredict
21  111313.02  120014.147705
30   99937.59   98378.492135
48   35673.41   49705.758604
23  108733.99  112251.256292
43   69758.98   58840.241994
44   65200.33   59175.932666
41   77798.83   75028.473441
8   152211.77  155729.981104
47   42559.73   40859.064408
49   14681.40   43839.176453
36   90708.19   74521.464332
42   71498.49   68889.428199
6   156122.51  156825.547180
10  146121.95  137362.541627
32   97427.84   95643.198894
16  126992.93  117072.982629
22  110352.25  116486.484015
11  144259.40  137104.488545
12  141585.52  130493.577509
31   97483.56   97204.262338
13  134307.35  127315.161024
33   96778.92   98788.097146
35   96479.51   93644.249632
14  132602.65  150551.205473
19  122776.86  114518.292424
38   81229.06   72650.206447
3   182901.99  180244.265522
9   149759.96  157069.933822
18  124266.90  131388.712062
2   191050.39  187891.368313
24  108552.04  115828.794229
7   155752.60  162548.107656
20  118474.03  117489.056180

# finding accuracy

In [102]:
from sklearn.metrics import r2_score

In [103]:
r2_score(ytrain,ytrainpredict)

0.9476932235812433

In [104]:
#loss
1-r2_score(ytrain,ytrainpredict)

0.052306776418756695

In [105]:
0.052306776418756695+0.9476932235812433

1.0

# now with test data

In [108]:
ytestpred=reg.predict(xtest)

In [109]:
ytestpred

array([170240.20683766, 118590.36972579,  90594.9709258 , 150344.50386679,
        72741.40312664,  45659.88568762, 177413.67939309,  99769.62212394,
       200083.09384003,  98669.21294956, 101653.7685308 ,  86488.54717965,
       133334.50770296,  83164.1000825 , 192577.75562918,  56460.54841536,
       109394.5677772 ])

In [111]:
print(len(xtest))
len(ytestpred)

17


17

# accuracy for test data

In [112]:
r2_score(ytest,ytestpred)

0.9386721159474758

In [113]:
#finding loss
1-r2_score(ytest,ytestpred)

0.061327884052524206

# now finding working of model with other data

In [115]:
xtrain.head()

R&D Spend  Administration  Marketing Spend  Florida  New York
21   78389.47       153773.43        299737.29        0         1
30   61994.48       115641.28         91131.24        1         0
48     542.05        51743.15             0.00        0         1
23   67532.53       105751.03        304768.73        1         0
43   15505.73       127382.30         35534.17        0         1

In [119]:
reg.predict([[61994.48,115641.28,91131.24,1,0]])

C:\Users\RGUKT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([98378.49213456])

In [ ]:
#ucan see 30 row in data set profit column is near to prdicted from model 

In [120]:
#data of realtime
reg.predict([[1.1,2.22,3.44,1,0]])

C:\Users\RGUKT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([50515.80812498])